# Generated by Django 5.2.7 on 2025-10-28 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('skill_created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_schedule', models.CharField(blank=True, max_length=50)),
                ('preferred_work_setup', models.CharField(blank=True, max_length=20)),
                ('location_radius_km', models.IntegerField(blank=True, null=True)),
                ('seeker_created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('years_experience', models.IntegerField(default=0)),
                ('profile_skill_created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_skill_updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.seekerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.skill')),
            ],
            options={
                'unique_together': {('seeker', 'skill')},
            },
        ),
    ]
